name: Generate code

on:
  push:
    branches:
      - "master2"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Run tox
        run: python generate
      